#ifndef FACE_HAAR_DETECTOR_GLOBAL_H
#define FACE_HAAR_DETECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FACE_HAAR_DETECTOR_LIBRARY)
#  define FACE_HAAR_DETECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FACE_HAAR_DETECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FACE_HAAR_DETECTOR_GLOBAL_H
